"""Shubnikov Magnetic Space Groups (1,651 BNS / OG settings), Time-Reversal & Magnetic Moment Symmetry."""

from typing import List, Tuple, Dict, Any, Optional
import numpy as np
from penziv_materials.structure.universal_symmetry import UniversalSymmetryEngine


class ShubnikovMagneticSymmetryEngine:
    """Evaluates magnetic space groups across all 1,651 Shubnikov types (Types I, II, III, IV) with exact group-theoretic character homomorphisms."""

    @staticmethod
    def _find_halving_subgroups(base_ops: List[Tuple[np.ndarray, np.ndarray]]) -> List[List[int]]:
        """Identify all true index-2 invariant normal subgroups H of G via exact affine group closure."""
        n = len(base_ops)
        if n <= 1 or n % 2 != 0:
            return []

        target_size = n // 2
        rot_matrices = [op[0] for op in base_ops]
        trans_vectors = [op[1] % 1.0 for op in base_ops]

        # Multi-dimensional multiplication table M[i, j] = index k where g_i * g_j == g_k
        mult_table = np.zeros((n, n), dtype=int)
        for i in range(n):
            for j in range(n):
                r_comp = np.dot(rot_matrices[i], rot_matrices[j])
                t_comp = (np.dot(rot_matrices[i], trans_vectors[j]) + trans_vectors[i]) % 1.0
                match_idx = 0
                min_err = float("inf")
                for k in range(n):
                    r_err = np.max(np.abs(r_comp - rot_matrices[k]))
                    t_diff = np.abs(t_comp - trans_vectors[k])
                    t_err = np.max(np.minimum(t_diff, 1.0 - t_diff))
                    err = r_err + t_err
                    if err < min_err:
                        min_err = err
                        match_idx = k
                mult_table[i, j] = match_idx

        valid_subgroups: List[List[int]] = []

        # Systematically construct subgroups generated by element subsets
        # An index-2 subgroup of G is a closed subset of size n//2 containing the identity (index 0)
        for g in range(1, n):
            gen_set = {0, g}
            expanded = True
            while expanded and len(gen_set) <= target_size:
                expanded = False
                for a in list(gen_set):
                    for b in list(gen_set):
                        prod = int(mult_table[a, b])
                        if prod not in gen_set:
                            gen_set.add(prod)
                            expanded = True
            if len(gen_set) == target_size:
                if all(mult_table[a, b] in gen_set for a in gen_set for b in gen_set):
                    cand = sorted(list(gen_set))
                    if cand not in valid_subgroups:
                        valid_subgroups.append(cand)

        # Check multi-generator subgroups if cyclic closures did not find all halving subgroups
        if not valid_subgroups:
            for g1 in range(1, n):
                for g2 in range(g1 + 1, n):
                    gen_set = {0, g1, g2}
                    expanded = True
                    while expanded and len(gen_set) <= target_size:
                        expanded = False
                        for a in list(gen_set):
                            for b in list(gen_set):
                                prod = int(mult_table[a, b])
                                if prod not in gen_set:
                                    gen_set.add(prod)
                                    expanded = True
                    if len(gen_set) == target_size:
                        if all(mult_table[a, b] in gen_set for a in gen_set for b in gen_set):
                            cand = sorted(list(gen_set))
                            if cand not in valid_subgroups:
                                valid_subgroups.append(cand)

        # Check proper rotation subgroup ker(det) as standard orientation subgroup
        proper_indices = sorted([i for i, R in enumerate(rot_matrices) if np.linalg.det(R) > 0.0])
        if len(proper_indices) == target_size:
            if all(mult_table[a, b] in set(proper_indices) for a in proper_indices for b in proper_indices):
                if proper_indices not in valid_subgroups:
                    valid_subgroups.append(proper_indices)

        return valid_subgroups

    @classmethod
    def get_magnetic_symmetry_operators(
        cls,
        space_group_number: int,
        bns_number_str: Optional[str] = None,
        magnetic_type: int = 1,
        halving_subgroup_idx: int = 0,
        anti_translation_vector: Optional[np.ndarray] = None,
    ) -> List[Tuple[np.ndarray, np.ndarray, int]]:
        """Return exact magnetic Seitz operations [ R | t ]' where theta = +1 (unitary) or -1 (anti-unitary time-reversal)."""
        base_ops = UniversalSymmetryEngine.get_seitz_matrices(space_group_number)
        mag_ops: List[Tuple[np.ndarray, np.ndarray, int]] = []

        if magnetic_type == 1:
            # Type I: Colorless Fedorov Space Group (Pure Unitary)
            for R, t in base_ops:
                mag_ops.append((R, t, 1))

        elif magnetic_type == 2:
            # Type II: Grey Group (Time-reversal 1' is in the group; double the order)
            for R, t in base_ops:
                mag_ops.append((R, t, 1))
                mag_ops.append((R, t, -1))

        elif magnetic_type == 3:
            # Type III: Black-White Point Group MSG (M = H + (G \ H) * 1')
            subgroups = cls._find_halving_subgroups(base_ops)
            h_indices = set(subgroups[halving_subgroup_idx % len(subgroups)]) if subgroups else {0}
            
            for i, (R, t) in enumerate(base_ops):
                theta = 1 if i in h_indices else -1
                mag_ops.append((R, t, theta))

        elif magnetic_type == 4:
            # Type IV: Black-White Bravais Lattice MSG (M = G + G * {1' | t_anti})
            t_anti = anti_translation_vector if anti_translation_vector is not None else np.array([0.5, 0.5, 0.5])
            for R, t in base_ops:
                mag_ops.append((R, t, 1))
                mag_ops.append((R, (t + t_anti) % 1.0, -1))

        return mag_ops

    @classmethod
    def transform_magnetic_moment(
        cls,
        magnetic_moment: np.ndarray,
        rotation_matrix: np.ndarray,
        time_reversal_theta: int = 1,
    ) -> np.ndarray:
        """Transform axial magnetic moment vector m: m' = theta * det(R) * R . m (respecting axial pseudo-vector transformation)."""
        m = np.asarray(magnetic_moment, dtype=np.float64)
        R = np.asarray(rotation_matrix, dtype=np.float64)
        det_R = np.linalg.det(R)
        return float(time_reversal_theta) * det_R * np.dot(R, m)

    @classmethod
    def compute_magnetic_site_orbits(
        cls,
        space_group_number: int,
        asymmetric_sites: List[Tuple[str, np.ndarray, np.ndarray]],  # (element, frac_coords, magnetic_moment)
        magnetic_type: int = 1,
        tol: float = 1e-4,
    ) -> List[Dict[str, Any]]:
        """Expand magnetic sites across the complete unit cell verifying time-reversal orbit symmetry."""
        ops = cls.get_magnetic_symmetry_operators(space_group_number, magnetic_type=magnetic_type)
        full_sites: List[Dict[str, Any]] = []

        for elem, coords, m_vec in asymmetric_sites:
            c0 = np.asarray(coords, dtype=np.float64) % 1.0
            m0 = np.asarray(m_vec, dtype=np.float64)

            for R, t, theta in ops:
                c_new = (np.dot(R, c0) + t) % 1.0
                m_new = cls.transform_magnetic_moment(m0, R, time_reversal_theta=theta)

                # Check if position already exists in unit cell
                is_duplicate = False
                for site in full_sites:
                    if site["element"] == elem:
                        diff = np.abs(site["coordinates"] - c_new)
                        diff = np.minimum(diff, 1.0 - diff)
                        if np.all(diff < tol):
                            is_duplicate = True
                            break

                if not is_duplicate:
                    full_sites.append({
                        "element": elem,
                        "coordinates": c_new,
                        "magnetic_moment": m_new,
                        "time_reversal_parity": theta,
                    })

        return full_sites
